services:
  userdb:
    image: postgres:latest
    container_name: userdb
    environment:
      - POSTGRES_DB=${USER_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "${USER_DB_PORT}:5432"

  communitydb:
    image: postgres:latest
    container_name: communitydb
    environment:
      - POSTGRES_DB=${COMMUNITY_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "${COMMUNITY_DB_PORT}:5432"

  newsdb:
    image: postgres:latest
    container_name: newsdb
    environment:
      - POSTGRES_DB=${NEWS_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "${NEWS_DB_PORT}:5432"